### ISSUE TITLE
Pre-Release Checklist

### ISSUE THREAD

**Issue by amandesai01** [The-Nirvana-Labs/SamvadAI#15]
- [x] Insert collection name into `EmbeddingToIndexesMilvusStep::run`
- [x] Fix casting: `perform_embeddings` -> `embedding_to_indexes` see: samvad/embedding/_cast.py
- [x] Fix casting: `embedding_to_indexes` -> `summarize_text` see: samvad/embedding/_cast.py
- [x] what should be value for `num_sentences` in last step?
